tap "goles/battery"
tap "homebrew/bundle"
tap "homebrew/core"

# Install GNU core utilities (those that come with macOS are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew "coreutils"
# Mac App Store CLI: https://github.com/mas-cli/mas
brew "mas"
brew "tmux"
brew "dockutil"
brew "imagemagick"
brew "vim"
